In [2]:
pip install --upgrade scikit-learn numpy

Requirement already satisfied: scikit-learn in /Users/chohasong/anaconda3/lib/python3.11/site-packages (1.5.2)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/01/18/d154dc1638803adf987910cdd07097d9c526663a55666a97c124d09fb96a/scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Using cached scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy in /Users/chohasong/anaconda3/lib/python3.11/site-packages (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Using cached scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl (8.1 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
Successfully installed scikit-learn-1.8.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install --upgrade scikit-learn numpy pyarrow

Requirement already satisfied: scikit-learn in /Users/chohasong/anaconda3/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy in /Users/chohasong/anaconda3/lib/python3.11/site-packages (2.4.4)
Requirement already satisfied: pyarrow in /Users/chohasong/anaconda3/lib/python3.11/site-packages (11.0.0)
Collecting pyarrow
  Obtaining dependency information for pyarrow from https://files.pythonhosted.org/packages/62/c9/a47ab7ece0d86cbe6678418a0fbd1ac4bb493b9184a3891dfa0e7f287ae0/pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (3.0 kB)
Requirement already satisfied: scipy>=1.10.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/chohasong/anaconda3/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl (35.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 34.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 11.0.0
    Uninstalling pyarrow-11.0.0:
      Successfully uninstalled pyarrow-11.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.55.0 requires pandas<3,>=1.4.0, but you have pandas 3.0.2 which is incompatible.
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
# load and manipulate data and for one hot encoding
import pandas as pd
# calculate mean and sd
import numpy as np
# xgboost
import xgboost as xgb

# split data
from sklearn.model_selection import train_test_split
# for scoring
from sklearn.metrics import balanced_accuracy_score, roc_auc_score, make_scorer
# cross validation
from sklearn.model_selection import GridSearchCV
# confusion matrix
from sklearn.metrics import confusion_matrix
# draw confusion matrix
from sklearn.metrics import ConfusionMatrixDisplay

In [7]:
df = pd.read_excel('Telco_customer_churn.xlsx')

In [8]:
# check the data
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [9]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

Last four variables contain exit interview information and shouldn't be used as a prediction, so we remove them.

In [ ]:
df.drop(['Churn Label','Churn Score','CLTV','Churn Reason'],
        axis=1, inplace=True) 
        # axis=1 means column inplace=True, modify df directly don't make a copy
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,1
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,1

Some columns only contain single value, so will not be useful for classification.

In [11]:
df['Count'].unique()

array([1])

In [12]:
df['Country'].unique()

<ArrowStringArray>
['United States']
Length: 1, dtype: str

In [14]:
df['State'].unique()

<ArrowStringArray>
['California']
Length: 1, dtype: str

In [ ]:
# city contains lots of city names; so we keep this
df['City'].unique()

<ArrowStringArray>
[    'Los Angeles',   'Beverly Hills', 'Huntington Park',         'Lynwood',
  'Marina Del Rey',       'Inglewood',    'Santa Monica',        'Torrance',
        'Whittier',        'La Habra',
 ...
      'Janesville',      'Litchfield',        'Loyalton',        'Madeline',
    'Markleeville',         'Milford',         'Calpine',        'Standish',
        'Tulelake',  'Olympic Valley']
Length: 1129, dtype: str